# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved

name: "reddiff"
deg: "deno"
awd: True
cond_awd: False
obs_weight: 1.0
grad_term_weight: 0.25
denoise_term_weight: "linear"    #"linear", "sqrt", "log", "square", "trunc_linear", "const", "power2over3"
sigma_y: 0.0
eta: 0.0
lr: 0.1
sigma_x0: 0.0
operator:
  sigma: 0.05
  scale_factor: 4
  kernel_size: 61
  gaussian_intensity: 3.0
  motion_intensity: 0.5
  oversample: 2.0
  hdr_scale: 2.0
  mask_len_range: [128, 129]
  mask_prob_range: [0.70, 0.71]
  margin: [32, 32]
  box_start: null
  box_mask_len: null
